project_id = "adevhdkpbelglaxfjvqr"

[functions.crm-chat]
verify_jwt = false

[functions.execute-workflow]
verify_jwt = true

[functions.process-automation-rules]
verify_jwt = false

[functions.enhance-prompt]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = false

[functions.execute-automation-rules]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = false

[functions.send-sequence-email]
verify_jwt = true

[functions.process-email-sequences]
verify_jwt = false
